### ISSUE TITLE
Support Templated dataSources

### ISSUE THREAD

**Issue by dOrgJelli** [daostack/subgraph#197]
https://github.com/graphprotocol/graph-node/pull/832

Here's my shot at a Checklist needed for this:
- [x] Update `generate-subgraph.js` to support `templates:`
- [x] Add templates to the mappings that will be creating them (`DAORegistry`, ?)
- [x] Ensure existing tests still run and nothing's broken.
- [ ] Add a test that deploys a new DAO, registers it in the registry, and verifys the subgraph is updated accordingly.

**Comment by dOrgJelli** [comment]
This is looking like it'll require a large refactor to ensure it's done correct.

Currently the subgraph has all pre-deployed contracts (as you know), which are embedded in the subgraph.yml. This new templated datasources feature should be used for all instance based contracts (non-universal). Doing this is a large refactor, and would change how the whole project looks and acts (ex: test initialization).

@ben-kaufman has offered to chat with me tomorrow about this all, so I'll see if my analysis is correct. Will respond back soon next steps.

**Comment by ben-kaufman** [comment]
Hi, thanks for opening this issue!
I would actually recommend using the `DAORegistry` (which is already supported to some extent) instead of listening directly to the `DaoCreator` contract. This is in order to prevent spamming the subgraph with DAOs which should not be tracked.

I'm still reading the Graph Node PRs which implemented this dynamic feature to see how to write those templates.
We should probably start by moving only a single contract, for example, the Avatar to this dynamic structure and see if it works well, then continue to the rest.

We can further discuss all of that in our call later today.

**Comment by leviadam** [comment]
Hi @dOrgJelli :)

I agree with @ben-kaufman. We need to start simple.
I think we can maybe work first on a repo with a simple example. This will be the best way to understand this new feature.
Also, I agree we should use [arc-hive](https://github.com/daostack/arc-hive).

**Comment by orenyodfat** [comment]
yes , on first phase we need a basic support for dynamically adding new daos (avatar, reputation,daotokens ,controller(if not using universal)). 

@dOrgJelli please note that Dao registry already indexed by the subgraph.

**Comment by dOrgJelli** [comment]
I've done some initial R&D around this and realized the changes needed don't need to be a refactor, but instead an addition to what's existing. The pre-deployment of DAOs (in the `daos` folder) doesn't need to be changed to use this new feature IMO. I've updated the above checklist to reflect the new plan, and have worked on executing it here:
https://github.com/dOrgTech/subgraph/pull/2

In response to "only indexing DAOs that're registered in the registry", it looks like this will result in all events fired before the registration to be lost. I'm creating tests to verify this is correct, but the explanation of the feature states this:
"Whenever we we process a block and mappings request new data sources, these data sources are collected and, after having processed the block, are instantiated from templates. We then process the current block again but only with those new data sources."
https://github.com/graphprotocol/graph-node/pull/832#issue-262803861

If this is in fact the case, I propose we'll need to start indexing these new DAOs when `DAOCreator.forgeOrg` is called to make sure we don't miss anything.

**Comment by dOrgJelli** [comment]
Also here is an example of what `ops/generate-subgraph.js` now outputs:
`subgraph.yaml`
```
- kind: ethereum/contract
    name: DAORegistry
    network: private
    source:
      address: '0x67B5656d60a809915323Bf2C40A8bEF15A152e3e'
      abi: DAORegistry
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.1
      language: wasm/assemblyscript
      file: src/mappings/DAORegistry/mapping.ts
      entities:
        - DAORegistryContract
      abis:
        - name: DAORegistry
          file: ./abis/DAORegistry.json
      eventHandlers:
        - event: Propose(address)
          handler: handlePropose
        - event: 'Register(address,string)'
          handler: handleRegister
        - event: UnRegister(address)
          handler: handleUnRegister
    templates:
      - kind: ethereum/contract
        name: Avatar
        network: private
        source:
          abi: Avatar
        mapping:
          kind: ethereum/events
          apiVersion: 0.0.1
          language: wasm/assemblyscript
          file: src/mappings/Avatar/mapping.ts
          entities:
            - AvatarContract
          abis:
            - name: Avatar
              file: ./abis/Avatar.json
          eventHandlers:
            - event: 'SendEther(uint256,address)'
              handler: handleSendEth
            - event: 'ReceiveEther(address,uint256)'
              handler: handleReceiveEth
      - kind: ethereum/contract
        name: Controller
        network: private
        source:
          abi: Controller
        mapping: ...
```
