### ISSUE TITLE
subgraph index does not seem to be complete

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/subgraph#415]
It seems that the `setupEnv` script is only partially indexing the data from `migration.json`.

This refers to release rc36.v1; driven, supposedly, by https://github.com/daostack/migration/blob/0.0.1-rc.36-v1/migration.json

Docker setup that I am testing with is below. 

There are two things that I noticed, but there may be more:

(a) not all DAOs in migration.json are indexed: I do not see https://github.com/daostack/migration/blob/0.0.1-rc.36-v1/migration.json#L1318 for example

(b) even if they are indexed, the proposals are not always indexed. For example, `Calimitous cookies` has no proposals at all: https://github.com/daostack/migration/blob/0.0.1-rc.36-v1/migration.json#L1335

This is the docker setup I am testing from:

```
version: "3"
services:
  graph-node:
    image: 'graphprotocol/graph-node:v0.16.1'
    ports:
      - 8000:8000
      - 8001:8001
      - 8020:8020
    links:
      - ipfs
      - postgres
      - ganache
    environment:
      postgres_host: postgres:5432
      postgres_user: postgres
      postgres_pass: 'letmein'
      postgres_db: postgres
      ipfs: ipfs:5001
      ethereum: private:http://ganache:8545
      GRAPH_LOG: "graph.log"
      GRAPH_GRAPHQL_MAX_FIRST: 1000

  ipfs:
    image: daostack/subgraph-ipfs:ganache-0.0.1-rc.36-v1-0.0.36-0
    ports:
      - 5001:5001

  postgres:
    image: daostack/subgraph-postgres:ganache-0.0.1-rc.36-v1-0.0.36-0
    ports:
      - 9432:5432
    environment:
      POSTGRES_PASSWORD: 'letmein'

  ganache:
    image: 'daostack/migration:0.0.1-rc.36-v1'
    ports:
      - 8545:8545
```
